images:
  auth_service: "dyremix/elib-authservice:latest"
  book_service: "dyremix/elib-bookservice:latest"
  user_service: "dyremix/elib-userservice:latest"
  apigateway: "dyremix/elib-apigateway:latest"

environment:
  database:
    connectionString: "Server=elib-postgres.postgres.database.azure.com;Port=5432;Database=postgres;User Id=PKadmin;Password=Biblioteka1234;"
  dockerURL:
    registryURL: "https://index.docker.io/v1"
  secrets:
    securityKey: "asfasfASFASF325%@#%#@"
  ServiceBus:
    "Endpoint=sb://azureservicebusforelib.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=NdDqokBDBN8QAQoKWxpL0TappKNsOVPmr+ASbKfPXSw="