image:
  repository: dyremix/elib-authservice
  tag: latest

container:
  port: 80

environment: Development

database:
  connectionString: "Server=elib-postgres.postgres.database.azure.com;Port=5432;Database=postgres;User Id=PKadmin;Password=Biblioteka1234;"

docker:
  registryURL: "https://index.docker.io/v1"

secrets:
  securityKey: "asfasfASFASF325%@#%#@"

appService:
  enableStorage: "false"

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30000