apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: e-library-book-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-book-service
  template:
    metadata:
      labels:
        app: e-library-book-service
    spec:
      containers:
      - name: e-library-book-service
        image: "{{ .Values.images.book_service }}"
        ports:
        - containerPort: 80
        - containerPort: 1234
        livenessProbe:
          httpGet:
            path: /WeatherForecast
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: ConnectionStrings__PostgresAuthDb
          value: "{{ .Values.environment.database.connectionString }}"
        - name: DOCKER_ENABLE_CI
          value: "true"
        - name: Flags__EnableUserFriendlyErrorMessages
          value: "1"
        - name: DOCKER_REGISTRY_SERVER_URL
          value: "{{ .Values.environment.dockerURL.registryURL }}"
        - name: Secrets__SecurityKey
          value: "{{ .Values.environment.secrets.securityKey }}"
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: "false"
        - name: Flags__UserRabbitMq
          value: "0"
        - name: AzureServiceBusConnectionString
          value: "{{ .Values.environment.ServiceBus }}"
---
apiVersion: v1
kind: Service
metadata:
  name: e-library-book-service
spec:
  type: ClusterIP
  selector:
    app: e-library-book-service
  ports:
  - name: main
    protocol: TCP
    port: 80
    targetPort: 80
  - name: metrics
    protocol: TCP
    port: 1234
    targetPort: 1234
