apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-library-auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-auth-service
  template:
    metadata:
      labels:
        app: e-library-auth-service
    spec:
      containers:
      - name: e-library-auth-service
        image: dyremix/elib-authservice:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: e-library-auth-service-service
spec:
  type: NodePort
  selector:
    app: e-library-auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
