apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-library-auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-auth-service
  template:
    metadata:
      labels:
        app: e-library-auth-service
    spec:
      containers:
      - name: e-library-auth-service
        image: dyremix/elib-authservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ConnectionStrings__PostgresAuthDb
          value: "Server=elib-postgres.postgres.database.azure.com;Port=5432;Database=postgres;User Id=PKadmin;Password=Biblioteka1234;"
        - name: DOCKER_REGISTRY_SERVER_URL
          value: "https://index.docker.io/v1"
        - name: Secrets__SecurityKey
          value: "asfasfASFASF325%@#%#@"
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: "false"
---

apiVersion: v1
kind: Service
metadata:
  name: e-library-auth-service-service
spec:
  type: NodePort
  selector:
    app: e-library-auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
