apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: e-library-apigateway-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-apigateway
  template:
    metadata:
      labels:
        app: e-library-apigateway
    spec:
      containers:
      - name: e-library-apigateway
        image: "{{ .Values.images.apigateway }}"
        ports:
        - containerPort: 80
        - containerPort: 1234
        env:
        - name: DOCKER_REGISTRY_SERVER_PASSWORD
          value: ""
        - name: DOCKER_REGISTRY_SERVER_USERNAME
          value: ""
        - name: DOCKER_REGISTRY_SERVER_URL
          value: "{{ .Values.environment.dockerURL.registryURL }}"
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: e-library-apigateway-service
spec:
  type: ClusterIP
  selector:
    app: e-library-apigateway-service
  ports:
  - name: main
    protocol: TCP
    port: 80
    targetPort: 80
  - name: metrics
    protocol: TCP
    port: 1234
    targetPort: 1234
