apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: e-library-auth-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-auth-service
  template:
    metadata:
      labels:
        app: e-library-auth-service
    spec:
      containers:
      - name: e-library-auth-service
        image: "{{ .Values.images.auth_service }}"
        ports:
        - containerPort: 80
        - containerPort: 1234
        livenessProbe:
          httpGet:
            path: /WeatherForecast
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AzureServiceBusConnectionString
          value: "{{ .Values.environment.ServiceBus }}"
        - name: ConnectionStrings__PostgresAuthDb
          value: "{{ .Values.environment.database.connectionString }}"
        - name: DOCKER_REGISTRY_SERVER_URL
          value: "{{ .Values.environment.dockerURL.registryURL }}"
        - name: Flags_UserRabbitMq
          value: "0"
        - name: Secrets__SecurityKey
          value: "{{ .Values.environment.secrets.securityKey }}"
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: e-library-auth-service
spec:
  type: ClusterIP
  selector:
    app: e-library-auth-service
  ports:
  - name: main
    protocol: TCP
    port: 80
    targetPort: 80
  - name: metrics
    protocol: TCP
    port: 1234
    targetPort: 1234
