apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: e-library-news-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-news-service
  template:
    metadata:
      labels:
        app: e-library-news-service
    spec:
      containers:
      - name: e-library-news-service
        image: "{{ .Values.images.news_service }}"
        # image: testowy_news
        # imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: e-library-news-service
spec:
  type: ClusterIP
  selector:
    app: e-library-news-service
  ports:
  - name: main
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 1234
    targetPort: 1234
