apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-library-auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-library-auth-service
  template:
    metadata:
      labels:
        app: e-library-auth-service
    spec:
      containers:
      - name: e-library-auth-service
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.container.port }}
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.environment }}
        - name: ConnectionStrings__PostgresAuthDb
          value: {{ .Values.database.connectionString }}
        - name: DOCKER_REGISTRY_SERVER_URL
          value: {{ .Values.docker.registryURL }}
        - name: Secrets__SecurityKey
          value: {{ .Values.secrets.securityKey }}
        - name: WEBSITES_ENABLE_APP_SERVICE_STORAGE
          value: {{ .Values.appService.enableStorage }}
---

apiVersion: v1
kind: Service
metadata:
  name: e-library-auth-service-service
spec:
  type: NodePort
  selector:
    app: e-library-auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
